//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Course", Namespace="http://schemas.datacontract.org/2004/07/Data")]
    [System.SerializableAttribute()]
    public partial class Course : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CourseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstructorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CourseId {
            get {
                return this.CourseIdField;
            }
            set {
                if ((this.CourseIdField.Equals(value) != true)) {
                    this.CourseIdField = value;
                    this.RaisePropertyChanged("CourseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstructorName {
            get {
                return this.InstructorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorNameField, value) != true)) {
                    this.InstructorNameField = value;
                    this.RaisePropertyChanged("InstructorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICourseService")]
    public interface ICourseService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetCourses", ReplyAction="http://tempuri.org/ICourseService/GetCoursesResponse")]
        CourseClient.ServiceReference1.Course[] GetCourses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetCourses", ReplyAction="http://tempuri.org/ICourseService/GetCoursesResponse")]
        System.Threading.Tasks.Task<CourseClient.ServiceReference1.Course[]> GetCoursesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetCourseById", ReplyAction="http://tempuri.org/ICourseService/GetCourseByIdResponse")]
        CourseClient.ServiceReference1.Course GetCourseById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/GetCourseById", ReplyAction="http://tempuri.org/ICourseService/GetCourseByIdResponse")]
        System.Threading.Tasks.Task<CourseClient.ServiceReference1.Course> GetCourseByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/AddCourse", ReplyAction="http://tempuri.org/ICourseService/AddCourseResponse")]
        void AddCourse(CourseClient.ServiceReference1.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/AddCourse", ReplyAction="http://tempuri.org/ICourseService/AddCourseResponse")]
        System.Threading.Tasks.Task AddCourseAsync(CourseClient.ServiceReference1.Course course);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/DeleteCourseById", ReplyAction="http://tempuri.org/ICourseService/DeleteCourseByIdResponse")]
        void DeleteCourseById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseService/DeleteCourseById", ReplyAction="http://tempuri.org/ICourseService/DeleteCourseByIdResponse")]
        System.Threading.Tasks.Task DeleteCourseByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICourseServiceChannel : CourseClient.ServiceReference1.ICourseService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CourseServiceClient : System.ServiceModel.ClientBase<CourseClient.ServiceReference1.ICourseService>, CourseClient.ServiceReference1.ICourseService {
        
        public CourseServiceClient() {
        }
        
        public CourseServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CourseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CourseClient.ServiceReference1.Course[] GetCourses() {
            return base.Channel.GetCourses();
        }
        
        public System.Threading.Tasks.Task<CourseClient.ServiceReference1.Course[]> GetCoursesAsync() {
            return base.Channel.GetCoursesAsync();
        }
        
        public CourseClient.ServiceReference1.Course GetCourseById(int id) {
            return base.Channel.GetCourseById(id);
        }
        
        public System.Threading.Tasks.Task<CourseClient.ServiceReference1.Course> GetCourseByIdAsync(int id) {
            return base.Channel.GetCourseByIdAsync(id);
        }
        
        public void AddCourse(CourseClient.ServiceReference1.Course course) {
            base.Channel.AddCourse(course);
        }
        
        public System.Threading.Tasks.Task AddCourseAsync(CourseClient.ServiceReference1.Course course) {
            return base.Channel.AddCourseAsync(course);
        }
        
        public void DeleteCourseById(int id) {
            base.Channel.DeleteCourseById(id);
        }
        
        public System.Threading.Tasks.Task DeleteCourseByIdAsync(int id) {
            return base.Channel.DeleteCourseByIdAsync(id);
        }
    }
}
